version: '3.9'

services:

  postgres:
  # Where can I found the dockerfile?
    build: '.'     
    environment:
      POSTGRES_USER: "posrtgres"
      POSTGRES_PASSWORD: "45665482"
      POSTGRES_DB: "myDb"
    restart: always
    volumes:
      - ./models/init.sql:/docker-entrypoint-initdb.d
    ports:
      - "54321:5432"
    command: [ "postgres" ]
 
  nats:
    image: "nats-streaming:0.9.2"
    restart: always
